# Generated by Django 4.0.6 on 2022-08-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
