# Generated by Django 4.0.6 on 2022-08-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personal_address_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='about2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
