# Generated by Django 4.0.6 on 2022-08-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personal_about2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='backgroundImage',
            field=models.ImageField(blank=True, default='banner.png', null=True, upload_to=''),
        ),
    ]
