# Generated by Django 4.0.6 on 2022-09-06 19:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_webinfo_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=app.models.user_directory_path),
        ),
    ]
