# Generated by Django 4.0.6 on 2022-09-06 21:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_personal_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='githubprofile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profile',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personal',
            name='upload',
            field=models.FileField(default='Nauman_Iftikhar_1.pdf', upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
    ]
